name: Suggestion
description: Make a suggestion
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      ### Use this form to suggest a feature.
- type: input
  attributes:
    label: Suggestion
    description: What do you want Minecraft Terminal to do?
  validations:
    required: true
- type: input
  attributes:
    label: Benefit
    description: Why do you need Minecraft Terminal to do this?
  validations:
    required: true
- type: checkboxes
  attributes:
    label: This suggestion is unique
    options:
    - label: I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.
      required: true
- type: textarea
  attributes:
    label: You may use the editor below to elaborate further.
