[RCON]
enabled = false
RegEx = "(?<=!#).+"
RegExFlags = ""

[commands]
commandPrompt = ">"
enableNonVanillaCMD = true

	[commands.autoComplete]
	enabled = true
	minLength = 1
	caseInsensitive = true
	RGBColor = [ 50, 60, 80 ]

	[commands.commandAliases]
	stopfollow = "unfollow"
	dist = "distance"
	ls = "list"
	break = "dig"
	stopdigging = "stopdig"
	put = "place"
	"a*" = "pathfind"
	"a*follow" = "smartfollow"
	chest = "open"
	cs = "changeslot"
	cd = "changeslot"
	use = "useitem"
	eval = "script"
	err = "error"
	ok = "success"
	"&" = "async"

[mineflayer.movements]
canDig = true
digCost = 3
placeCost = 3
liquidCost = 2
entityCost = 1
dontCreateFlow = true
dontMineUnderFallingBlock = true
allow1by1towers = true
allowFreeMotion = false
allowParkour = true
allowSprinting = true
allowEntityDetection = true
canOpenDoors = true
maxDropDown = 4
infiniteLiquidDropdownDistance = true

	[mineflayer.movements.bot]
	physicsEnabled = true

		[mineflayer.movements.bot.settings]
		chat = "enabled"
		colorsEnabled = true
		viewDistance = "far"
		mainHand = "left"
		enableTextFiltering = false
		enableServerListing = false

			[mineflayer.movements.bot.settings.skinParts]
			showCape = true
			showJacket = true
			showLeftSleeve = true
			showRightSleeve = true
			showLeftPants = true
			showRightPants = true
			showHat = true

		[mineflayer.movements.bot.pathfinder]
		thinkTimeout = 8_000
		tickTimeout = 40
		searchRadius = -1
		enablePathShortcut = true
		LOSWhenPlacingBlocks = true
